// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Groq.OpenApiClient.Openai.V1.Audio;
using Soenneker.Groq.OpenApiClient.Openai.V1.Batches;
using Soenneker.Groq.OpenApiClient.Openai.V1.Chat;
using Soenneker.Groq.OpenApiClient.Openai.V1.Embeddings;
using Soenneker.Groq.OpenApiClient.Openai.V1.Files;
using Soenneker.Groq.OpenApiClient.Openai.V1.ModelsRequests;
using Soenneker.Groq.OpenApiClient.Openai.V1.Reranking;
using Soenneker.Groq.OpenApiClient.Openai.V1.Responses;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Groq.OpenApiClient.Openai.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \openai\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The audio property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Audio.AudioRequestBuilder Audio
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Audio.AudioRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batches property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Batches.BatchesRequestBuilder Batches
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Batches.BatchesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chat property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Chat.ChatRequestBuilder Chat
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The embeddings property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Embeddings.EmbeddingsRequestBuilder Embeddings
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Embeddings.EmbeddingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The models property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.ModelsRequests.ModelsRequestBuilder Models
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.ModelsRequests.ModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reranking property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Reranking.RerankingRequestBuilder Reranking
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Reranking.RerankingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The responses property</summary>
        public global::Soenneker.Groq.OpenApiClient.Openai.V1.Responses.ResponsesRequestBuilder Responses
        {
            get => new global::Soenneker.Groq.OpenApiClient.Openai.V1.Responses.ResponsesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Openai.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/openai/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Openai.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/openai/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
