// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The type of annotation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AnnotationType
    {
        [EnumMember(Value = "document_citation")]
        #pragma warning disable CS1591
        DocumentCitation,
        #pragma warning restore CS1591
        [EnumMember(Value = "function_citation")]
        #pragma warning disable CS1591
        FunctionCitation,
        #pragma warning restore CS1591
    }
}
