// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The intended purpose of the uploaded file.Use &quot;batch&quot; for [Batch API](/docs/api-reference#batches).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchPurpose
    {
        [EnumMember(Value = "batch")]
        #pragma warning disable CS1591
        Batch,
        #pragma warning restore CS1591
    }
}
