// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Chart : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The chart elements (data series, points, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChartElement>? Elements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChartElement> Elements { get; set; }
#endif
        /// <summary>The title of the chart</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type of chart</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ChartType? Type { get; set; }
        /// <summary>The label for the x-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XLabel { get; set; }
#nullable restore
#else
        public string XLabel { get; set; }
#endif
        /// <summary>The scale type for the x-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XScale { get; set; }
#nullable restore
#else
        public string XScale { get; set; }
#endif
        /// <summary>The labels for the x-axis ticks</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? XTickLabels { get; set; }
#nullable restore
#else
        public List<string> XTickLabels { get; set; }
#endif
        /// <summary>The tick values for the x-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? XTicks { get; set; }
#nullable restore
#else
        public List<double?> XTicks { get; set; }
#endif
        /// <summary>The unit for the x-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XUnit { get; set; }
#nullable restore
#else
        public string XUnit { get; set; }
#endif
        /// <summary>The label for the y-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YLabel { get; set; }
#nullable restore
#else
        public string YLabel { get; set; }
#endif
        /// <summary>The scale type for the y-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YScale { get; set; }
#nullable restore
#else
        public string YScale { get; set; }
#endif
        /// <summary>The labels for the y-axis ticks</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? YTickLabels { get; set; }
#nullable restore
#else
        public List<string> YTickLabels { get; set; }
#endif
        /// <summary>The tick values for the y-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? YTicks { get; set; }
#nullable restore
#else
        public List<double?> YTicks { get; set; }
#endif
        /// <summary>The unit for the y-axis</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YUnit { get; set; }
#nullable restore
#else
        public string YUnit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.Chart"/> and sets the default values.
        /// </summary>
        public Chart()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.Chart"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.Chart CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.Chart();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "elements", n => { Elements = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChartElement>(global::Soenneker.Groq.OpenApiClient.Models.ChartElement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ChartType>(); } },
                { "x_label", n => { XLabel = n.GetStringValue(); } },
                { "x_scale", n => { XScale = n.GetStringValue(); } },
                { "x_tick_labels", n => { XTickLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "x_ticks", n => { XTicks = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "x_unit", n => { XUnit = n.GetStringValue(); } },
                { "y_label", n => { YLabel = n.GetStringValue(); } },
                { "y_scale", n => { YScale = n.GetStringValue(); } },
                { "y_tick_labels", n => { YTickLabels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "y_ticks", n => { YTicks = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "y_unit", n => { YUnit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChartElement>("elements", Elements);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ChartType>("type", Type);
            writer.WriteStringValue("x_label", XLabel);
            writer.WriteStringValue("x_scale", XScale);
            writer.WriteCollectionOfPrimitiveValues<string>("x_tick_labels", XTickLabels);
            writer.WriteCollectionOfPrimitiveValues<double?>("x_ticks", XTicks);
            writer.WriteStringValue("x_unit", XUnit);
            writer.WriteStringValue("y_label", YLabel);
            writer.WriteStringValue("y_scale", YScale);
            writer.WriteCollectionOfPrimitiveValues<string>("y_tick_labels", YTickLabels);
            writer.WriteCollectionOfPrimitiveValues<double?>("y_ticks", YTicks);
            writer.WriteStringValue("y_unit", YUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
