// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChartElement : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The angle for this element</summary>
        public double? Angle { get; set; }
        /// <summary>The first quartile value for this element</summary>
        public double? FirstQuartile { get; set; }
        /// <summary>The group this element belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Group { get; set; }
#nullable restore
#else
        public string Group { get; set; }
#endif
        /// <summary>The label for this chart element</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>The max property</summary>
        public double? Max { get; set; }
        /// <summary>The median value for this element</summary>
        public double? Median { get; set; }
        /// <summary>The minimum value for this element</summary>
        public double? Min { get; set; }
        /// <summary>The outliers for this element</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Outliers { get; set; }
#nullable restore
#else
        public List<double?> Outliers { get; set; }
#endif
        /// <summary>The points for this element</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Points { get; set; }
#nullable restore
#else
        public UntypedNode Points { get; set; }
#endif
        /// <summary>The radius for this element</summary>
        public double? Radius { get; set; }
        /// <summary>The third quartile value for this element</summary>
        public double? ThirdQuartile { get; set; }
        /// <summary>The value for this element</summary>
        public double? Value { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChartElement"/> and sets the default values.
        /// </summary>
        public ChartElement()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChartElement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ChartElement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ChartElement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "angle", n => { Angle = n.GetDoubleValue(); } },
                { "first_quartile", n => { FirstQuartile = n.GetDoubleValue(); } },
                { "group", n => { Group = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "max", n => { Max = n.GetDoubleValue(); } },
                { "median", n => { Median = n.GetDoubleValue(); } },
                { "min", n => { Min = n.GetDoubleValue(); } },
                { "outliers", n => { Outliers = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "points", n => { Points = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "radius", n => { Radius = n.GetDoubleValue(); } },
                { "third_quartile", n => { ThirdQuartile = n.GetDoubleValue(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("angle", Angle);
            writer.WriteDoubleValue("first_quartile", FirstQuartile);
            writer.WriteStringValue("group", Group);
            writer.WriteStringValue("label", Label);
            writer.WriteDoubleValue("max", Max);
            writer.WriteDoubleValue("median", Median);
            writer.WriteDoubleValue("min", Min);
            writer.WriteCollectionOfPrimitiveValues<double?>("outliers", Outliers);
            writer.WriteObjectValue<UntypedNode>("points", Points);
            writer.WriteDoubleValue("radius", Radius);
            writer.WriteDoubleValue("third_quartile", ThirdQuartile);
            writer.WriteDoubleValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
