// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The type of chart</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChartType
    {
        [EnumMember(Value = "bar")]
        #pragma warning disable CS1591
        Bar,
        #pragma warning restore CS1591
        [EnumMember(Value = "box_and_whisker")]
        #pragma warning disable CS1591
        BoxAndWhisker,
        #pragma warning restore CS1591
        [EnumMember(Value = "line")]
        #pragma warning disable CS1591
        Line,
        #pragma warning restore CS1591
        [EnumMember(Value = "pie")]
        #pragma warning disable CS1591
        Pie,
        #pragma warning restore CS1591
        [EnumMember(Value = "scatter")]
        #pragma warning disable CS1591
        Scatter,
        #pragma warning restore CS1591
        [EnumMember(Value = "superchart")]
        #pragma warning disable CS1591
        Superchart,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
