// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatCompletionResponseMessage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of annotations providing citations and references for the content in the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.Annotation>? Annotations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.Annotation> Annotations { get; set; }
#endif
        /// <summary>The contents of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>A list of tools that were executed during the chat completion for compound AI systems.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem>? ExecutedTools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem> ExecutedTools { get; set; }
#endif
        /// <summary>Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageFunctionCall? FunctionCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageFunctionCall FunctionCall { get; set; }
#endif
        /// <summary>The model&apos;s reasoning for a response. Only available for [models that support reasoning](https://console.groq.com/docs/reasoning) when request parameter reasoning_format has value `parsed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reasoning { get; set; }
#nullable restore
#else
        public string Reasoning { get; set; }
#endif
        /// <summary>The role of the author of this message.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageRole? Role { get; set; }
        /// <summary>The tool calls generated by the model, such as function calls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall>? ToolCalls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall> ToolCalls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessage"/> and sets the default values.
        /// </summary>
        public ChatCompletionResponseMessage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.Annotation>(global::Soenneker.Groq.OpenApiClient.Models.Annotation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "executed_tools", n => { ExecutedTools = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "function_call", n => { FunctionCall = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageFunctionCall>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageFunctionCall.CreateFromDiscriminatorValue); } },
                { "reasoning", n => { Reasoning = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageRole>(); } },
                { "tool_calls", n => { ToolCalls = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.Annotation>("annotations", Annotations);
            writer.WriteStringValue("content", Content);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem>("executed_tools", ExecutedTools);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageFunctionCall>("function_call", FunctionCall);
            writer.WriteStringValue("reasoning", Reasoning);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionResponseMessageRole>("role", Role);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall>("tool_calls", ToolCalls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
