// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionNamedToolChoice"/>, <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOptionWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatCompletionToolChoiceOption : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionNamedToolChoice"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionNamedToolChoice? ChatCompletionNamedToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionNamedToolChoice ChatCompletionNamedToolChoice { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOptionWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOptionWrapper? ChatCompletionToolChoiceOptionWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOptionWrapper ChatCompletionToolChoiceOptionWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption();
            if("ChatCompletionNamedToolChoice".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ChatCompletionNamedToolChoice = new global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionNamedToolChoice();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ChatCompletionNamedToolChoice != null)
            {
                return ChatCompletionNamedToolChoice.GetFieldDeserializers();
            }
            else if(ChatCompletionToolChoiceOptionWrapper != null)
            {
                return ChatCompletionToolChoiceOptionWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ChatCompletionNamedToolChoice != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionNamedToolChoice>(null, ChatCompletionNamedToolChoice);
            }
            else if(ChatCompletionToolChoiceOptionWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOptionWrapper>(null, ChatCompletionToolChoiceOptionWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
