// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionMessageExecutedToolsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The arguments passed to the tool in JSON format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Arguments { get; set; }
#nullable restore
#else
        public string Arguments { get; set; }
#endif
        /// <summary>Array of browser results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.BrowserResult>? BrowserResults { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.BrowserResult> BrowserResults { get; set; }
#endif
        /// <summary>Array of code execution results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult>? CodeResults { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult> CodeResults { get; set; }
#endif
        /// <summary>The index of the executed tool.</summary>
        public int? Index { get; set; }
        /// <summary>The output returned by the tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Output { get; set; }
#nullable restore
#else
        public string Output { get; set; }
#endif
        /// <summary>The search results returned by the tool, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItemSearchResults? SearchResults { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItemSearchResults SearchResults { get; set; }
#endif
        /// <summary>The type of tool that was executed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem"/> and sets the default values.
        /// </summary>
        public ChatCompletionMessageExecutedToolsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "arguments", n => { Arguments = n.GetStringValue(); } },
                { "browser_results", n => { BrowserResults = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.BrowserResult>(global::Soenneker.Groq.OpenApiClient.Models.BrowserResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "code_results", n => { CodeResults = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult>(global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "output", n => { Output = n.GetStringValue(); } },
                { "search_results", n => { SearchResults = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItemSearchResults>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItemSearchResults.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("arguments", Arguments);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.BrowserResult>("browser_results", BrowserResults);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult>("code_results", CodeResults);
            writer.WriteIntValue("index", Index);
            writer.WriteStringValue("output", Output);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageExecutedToolsItemSearchResults>("search_results", SearchResults);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
