// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionRequestAssistantMessage : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageContent? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageContent Content { get; set; }
#endif
        /// <summary>Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageFunctionCall? FunctionCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageFunctionCall FunctionCall { get; set; }
#endif
        /// <summary>An optional name for the participant. Provides the model information to differentiate between participants of the same role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The reasoning output by the assistant if reasoning_format was set to &apos;parsed&apos;.This field is supported on [models that support reasoning](https://console.groq.com/docs/reasoning).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reasoning { get; set; }
#nullable restore
#else
        public string Reasoning { get; set; }
#endif
        /// <summary>The role of the messages author, in this case `assistant`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.AssistantRole? Role { get; set; }
        /// <summary>The tool calls generated by the model, such as function calls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall>? ToolCalls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall> ToolCalls { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageContent>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageContent.CreateFromDiscriminatorValue); } },
                { "function_call", n => { FunctionCall = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageFunctionCall>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageFunctionCall.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "reasoning", n => { Reasoning = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.AssistantRole>(); } },
                { "tool_calls", n => { ToolCalls = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageContent>("content", Content);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestAssistantMessageFunctionCall>("function_call", FunctionCall);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("reasoning", Reasoning);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.AssistantRole>("role", Role);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionMessageToolCall>("tool_calls", ToolCalls);
        }
    }
}
#pragma warning restore CS0618
