// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The type of the tool. `function`, `browser_search`, and `code_interpreter` are supported.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionToolTypeWrapperValue
    {
        [EnumMember(Value = "function")]
        #pragma warning disable CS1591
        Function,
        #pragma warning restore CS1591
        [EnumMember(Value = "browser_search")]
        #pragma warning disable CS1591
        BrowserSearch,
        #pragma warning restore CS1591
        [EnumMember(Value = "code_interpreter")]
        #pragma warning disable CS1591
        CodeInterpreter,
        #pragma warning restore CS1591
    }
}
