// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionRequestUserMessage : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The contents of the user message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageContent? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageContent Content { get; set; }
#endif
        /// <summary>An optional name for the participant. Provides the model information to differentiate between participants of the same role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The role of the messages author, in this case `user`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageRole? Role { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageContent>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageContent.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageRole>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageContent>("content", Content);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestUserMessageRole>("role", Role);
        }
    }
}
#pragma warning restore CS0618
