// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>Identifies this document source as JSON data.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionDocumentSourceJsonType
    {
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
    }
}
