// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CodeExecutionResult : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The chart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.Chart? Chart { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.Chart Chart { get; set; }
#endif
        /// <summary>Array of charts from a superchart</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.Chart>? Charts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.Chart> Charts { get; set; }
#endif
        /// <summary>Base64 encoded PNG image output from code execution</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Png { get; set; }
#nullable restore
#else
        public string Png { get; set; }
#endif
        /// <summary>The text version of the code execution result</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CodeExecutionResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chart", n => { Chart = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.Chart>(global::Soenneker.Groq.OpenApiClient.Models.Chart.CreateFromDiscriminatorValue); } },
                { "charts", n => { Charts = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.Chart>(global::Soenneker.Groq.OpenApiClient.Models.Chart.CreateFromDiscriminatorValue)?.AsList(); } },
                { "png", n => { Png = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.Chart>("chart", Chart);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.Chart>("charts", Charts);
            writer.WriteStringValue("png", Png);
            writer.WriteStringValue("text", Text);
        }
    }
}
#pragma warning restore CS0618
