// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Usage statistics for the completion request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompletionUsage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Time spent generating tokens</summary>
        public double? CompletionTime { get; set; }
        /// <summary>Number of tokens in the generated completion.</summary>
        public int? CompletionTokens { get; set; }
        /// <summary>Breakdown of tokens in the completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CompletionUsageCompletionTokensDetails? CompletionTokensDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CompletionUsageCompletionTokensDetails CompletionTokensDetails { get; set; }
#endif
        /// <summary>Time spent processing input tokens</summary>
        public double? PromptTime { get; set; }
        /// <summary>Number of tokens in the prompt.</summary>
        public int? PromptTokens { get; set; }
        /// <summary>Breakdown of tokens in the prompt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CompletionUsagePromptTokensDetails? PromptTokensDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CompletionUsagePromptTokensDetails PromptTokensDetails { get; set; }
#endif
        /// <summary>Time the requests was spent queued</summary>
        public double? QueueTime { get; set; }
        /// <summary>completion time and prompt time combined</summary>
        public double? TotalTime { get; set; }
        /// <summary>Total number of tokens used in the request (prompt + completion).</summary>
        public int? TotalTokens { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage"/> and sets the default values.
        /// </summary>
        public CompletionUsage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completion_time", n => { CompletionTime = n.GetDoubleValue(); } },
                { "completion_tokens", n => { CompletionTokens = n.GetIntValue(); } },
                { "completion_tokens_details", n => { CompletionTokensDetails = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CompletionUsageCompletionTokensDetails>(global::Soenneker.Groq.OpenApiClient.Models.CompletionUsageCompletionTokensDetails.CreateFromDiscriminatorValue); } },
                { "prompt_time", n => { PromptTime = n.GetDoubleValue(); } },
                { "prompt_tokens", n => { PromptTokens = n.GetIntValue(); } },
                { "prompt_tokens_details", n => { PromptTokensDetails = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CompletionUsagePromptTokensDetails>(global::Soenneker.Groq.OpenApiClient.Models.CompletionUsagePromptTokensDetails.CreateFromDiscriminatorValue); } },
                { "queue_time", n => { QueueTime = n.GetDoubleValue(); } },
                { "total_time", n => { TotalTime = n.GetDoubleValue(); } },
                { "total_tokens", n => { TotalTokens = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("completion_time", CompletionTime);
            writer.WriteIntValue("completion_tokens", CompletionTokens);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CompletionUsageCompletionTokensDetails>("completion_tokens_details", CompletionTokensDetails);
            writer.WriteDoubleValue("prompt_time", PromptTime);
            writer.WriteIntValue("prompt_tokens", PromptTokens);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CompletionUsagePromptTokensDetails>("prompt_tokens_details", PromptTokensDetails);
            writer.WriteDoubleValue("queue_time", QueueTime);
            writer.WriteDoubleValue("total_time", TotalTime);
            writer.WriteIntValue("total_tokens", TotalTokens);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
