// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateChatCompletionRequestModelWrapperValue
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "compound-beta")]
        #pragma warning disable CS1591
        CompoundBeta,
        #pragma warning restore CS1591
        [EnumMember(Value = "compound-beta-mini")]
        #pragma warning disable CS1591
        CompoundBetaMini,
        #pragma warning restore CS1591
        [EnumMember(Value = "gemma2-9b-it")]
        #pragma warning disable CS1591
        Gemma29BIt,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama-3.1-8b-instant")]
        #pragma warning disable CS1591
        Llama318BInstant,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama-3.3-70b-versatile")]
        #pragma warning disable CS1591
        Llama3370BVersatile,
        #pragma warning restore CS1591
        [EnumMember(Value = "meta-llama/llama-4-maverick-17b-128e-instruct")]
        #pragma warning disable CS1591
        MetaLlamaLlama4Maverick17B128EInstruct,
        #pragma warning restore CS1591
        [EnumMember(Value = "meta-llama/llama-4-scout-17b-16e-instruct")]
        #pragma warning disable CS1591
        MetaLlamaLlama4Scout17B16EInstruct,
        #pragma warning restore CS1591
        [EnumMember(Value = "meta-llama/llama-guard-4-12b")]
        #pragma warning disable CS1591
        MetaLlamaLlamaGuard412B,
        #pragma warning restore CS1591
        [EnumMember(Value = "moonshotai/kimi-k2-instruct")]
        #pragma warning disable CS1591
        MoonshotaiKimiK2Instruct,
        #pragma warning restore CS1591
        [EnumMember(Value = "openai/gpt-oss-120b")]
        #pragma warning disable CS1591
        OpenaiGptOss120B,
        #pragma warning restore CS1591
        [EnumMember(Value = "openai/gpt-oss-20b")]
        #pragma warning disable CS1591
        OpenaiGptOss20B,
        #pragma warning restore CS1591
        [EnumMember(Value = "qwen/qwen3-32b")]
        #pragma warning disable CS1591
        QwenQwen332B,
        #pragma warning restore CS1591
        [EnumMember(Value = "qwen/qwen3.6-27b")]
        #pragma warning disable CS1591
        QwenQwen3627B,
        #pragma warning restore CS1591
    }
}
