// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateBatchRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time frame within which the batch should be processed. Durations from `24h` to `7d` are supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompletionWindow { get; set; }
#nullable restore
#else
        public string CompletionWindow { get; set; }
#endif
        /// <summary>The endpoint to be used for all requests in the batch. Currently `/v1/chat/completions` is supported.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.V1ChatCompletionsEndpoint? Endpoint { get; set; }
        /// <summary>The ID of an uploaded file that contains requests for the new batch.See [upload file](/docs/api-reference#files-upload) for how to upload a file.Your input file must be formatted as a [JSONL file](/docs/batch), and must be uploaded with the purpose `batch`. The file can be up to 100 MB in size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputFileId { get; set; }
#nullable restore
#else
        public string InputFileId { get; set; }
#endif
        /// <summary>Optional custom metadata for the batch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequestMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequestMetadata Metadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequest"/> and sets the default values.
        /// </summary>
        public CreateBatchRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completion_window", n => { CompletionWindow = n.GetStringValue(); } },
                { "endpoint", n => { Endpoint = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.V1ChatCompletionsEndpoint>(); } },
                { "input_file_id", n => { InputFileId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequestMetadata>(global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequestMetadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("completion_window", CompletionWindow);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.V1ChatCompletionsEndpoint>("endpoint", Endpoint);
            writer.WriteStringValue("input_file_id", InputFileId);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateBatchRequestMetadata>("metadata", Metadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
