// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Custom configuration of models and tools for Compound.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateChatCompletionRequestCompoundCustom : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The models property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomModels? Models { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomModels Models { get; set; }
#endif
        /// <summary>Configuration options for tools available to Compound.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomTools? Tools { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomTools Tools { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom"/> and sets the default values.
        /// </summary>
        public CreateChatCompletionRequestCompoundCustom()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "models", n => { Models = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomModels>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomModels.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomTools>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomTools.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomModels>("models", Models);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustomTools>("tools", Tools);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
