// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateSpeechRequestModelWrapperValue
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "playai-tts")]
        #pragma warning disable CS1591
        PlayaiTts,
        #pragma warning restore CS1591
        [EnumMember(Value = "playai-tts-arabic")]
        #pragma warning disable CS1591
        PlayaiTtsArabic,
        #pragma warning restore CS1591
    }
}
