// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateChatCompletionRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether to enable citations in the response. When enabled, the model will include citations for information retrieved from provided documents or web searches.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCitationOptions? CitationOptions { get; set; }
        /// <summary>Custom configuration of models and tools for Compound.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom? CompoundCustom { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom CompoundCustom { get; set; }
#endif
        /// <summary>If set to true, groq will return called tools without validating that the tool is present in request.tools. tool_choice=required/none will still be enforced, but the request cannot require a specific tool be used.</summary>
        public bool? DisableToolValidation { get; set; }
        /// <summary>A list of documents to provide context for the conversation. Each document contains text that can be referenced by the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionDocument>? Documents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionDocument> Documents { get; set; }
#endif
        /// <summary>&quot;Deprecated: Use search_settings.exclude_domains instead.A list of domains to exclude from the search results when the model uses a web search tool.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeDomains { get; set; }
#nullable restore
#else
        public List<string> ExcludeDomains { get; set; }
#endif
        /// <summary>This is not yet supported by any of our models. Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model&apos;s likelihood to repeat the same line verbatim.</summary>
        public double? FrequencyPenalty { get; set; }
        /// <summary>&quot;Deprecated in favor of `tool_choice`.Controls which (if any) function is called by the model.`none` means the model will not call a function and instead generates a message.`auto` means the model can pick between generating a message or calling a function.Specifying a particular function via `{\&quot;name\&quot;: \&quot;my_function\&quot;}` forces the model to call that function.`none` is the default when no functions are present. `auto` is the default if functions are present.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestFunctionCall? FunctionCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestFunctionCall FunctionCall { get; set; }
#endif
        /// <summary>Deprecated in favor of `tools`.A list of functions the model may generate JSON inputs for.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionFunctions>? Functions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionFunctions> Functions { get; set; }
#endif
        /// <summary>&quot;Deprecated: Use search_settings.include_domains instead.A list of domains to include in the search results when the model uses a web search tool.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncludeDomains { get; set; }
#nullable restore
#else
        public List<string> IncludeDomains { get; set; }
#endif
        /// <summary>Whether to include reasoning in the response.  If true, the response will include a `reasoning` field. If false, the model&apos;s reasoning will not be included in the response.This field is mutually exclusive with `reasoning_format`.</summary>
        public bool? IncludeReasoning { get; set; }
        /// <summary>This is not yet supported by any of our models.Modify the likelihood of specified tokens appearing in the completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestLogitBiasProperty? LogitBias { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestLogitBiasProperty LogitBias { get; set; }
#endif
        /// <summary>This is not yet supported by any of our models.Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`.</summary>
        public bool? Logprobs { get; set; }
        /// <summary>The maximum number of tokens that can be generated in the chat completion. The total length of input tokens and generated tokens is limited by the model&apos;s context length.</summary>
        public int? MaxCompletionTokens { get; set; }
        /// <summary>Deprecated in favor of `max_completion_tokens`.The maximum number of tokens that can be generated in the chat completion. The total length of input tokens and generated tokens is limited by the model&apos;s context length.</summary>
        [Obsolete("")]
        public int? MaxTokens { get; set; }
        /// <summary>A list of messages comprising the conversation so far.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestMessage> Messages { get; set; }
#endif
        /// <summary>This parameter is not currently supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestMetadataProperty Metadata { get; set; }
#endif
        /// <summary>ID of the model to use. For details on which models are compatible with the Chat API, see available [models](https://console.groq.com/docs/models)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestModel? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestModel Model { get; set; }
#endif
        /// <summary>How many chat completion choices to generate for each input message. Note that the current moment, only n=1 is supported. Other values will result in a 400 response.</summary>
        public int? N { get; set; }
        /// <summary>Whether to enable parallel function calling during tool use.</summary>
        public bool? ParallelToolCalls { get; set; }
        /// <summary>This is not yet supported by any of our models. Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model&apos;s likelihood to talk about new topics.</summary>
        public double? PresencePenalty { get; set; }
        /// <summary>qwen3 models support the following valuesSet to &apos;none&apos; to disable reasoning.Set to &apos;default&apos; or null to let Qwen reason.openai/gpt-oss-20b and openai/gpt-oss-120b support &apos;low&apos;, &apos;medium&apos;, or &apos;high&apos;.&apos;medium&apos; is the default value.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestReasoningEffort? ReasoningEffort { get; set; }
        /// <summary>Specifies how to output reasoning tokensThis field is mutually exclusive with `include_reasoning`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestReasoningFormat? ReasoningFormat { get; set; }
        /// <summary>&quot;An object specifying the format that the model must output. Setting to `{ \&quot;type\&quot;: \&quot;json_schema\&quot;, \&quot;json_schema\&quot;: {...} }` enables Structured Outputs which ensures the model will match your supplied JSON schema. `json_schema` response format is only available on [supported models](https://console.groq.com/docs/structured-outputs#supported-models). Setting to `{ \&quot;type\&quot;: \&quot;json_object\&quot; }` enables the older JSON mode, which ensures the message the model generates is valid JSON. Using `json_schema` is preferred for models that support it.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestResponseFormat? ResponseFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestResponseFormat ResponseFormat { get; set; }
#endif
        /// <summary>Settings for web search functionality when the model uses a web search tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestSearchSettings? SearchSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestSearchSettings SearchSettings { get; set; }
#endif
        /// <summary>If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.</summary>
        public int? Seed { get; set; }
        /// <summary>The service tier to use for the request. Defaults to `on_demand`.- `auto` will automatically select the highest tier available within the rate limits of your organization.- `flex` uses the flex tier, which will succeed or fail quickly.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestServiceTier? ServiceTier { get; set; }
        /// <summary>Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestStop? Stop { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestStop Stop { get; set; }
#endif
        /// <summary>This parameter is not currently supported.</summary>
        public bool? Store { get; set; }
        /// <summary>&quot;If set, partial message deltas will be sent. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example code](/docs/text-chat#streaming-a-chat-completion).&quot;</summary>
        public bool? Stream { get; set; }
        /// <summary>What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.</summary>
        public double? Temperature { get; set; }
        /// <summary>&quot;Controls which (if any) tool is called by the model.`none` means the model will not call any tool and instead generates a message.`auto` means the model can pick between generating a message or calling one or more tools.`required` means the model must call one or more tools.Specifying a particular tool via `{\&quot;type\&quot;: \&quot;function\&quot;, \&quot;function\&quot;: {\&quot;name\&quot;: \&quot;my_function\&quot;}}` forces the model to call that tool.`none` is the default when no tools are present. `auto` is the default if tools are present.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption ToolChoice { get; set; }
#endif
        /// <summary>A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionTool> Tools { get; set; }
#endif
        /// <summary>This is not yet supported by any of our models.An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.</summary>
        public int? TopLogprobs { get; set; }
        /// <summary>An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both.</summary>
        public double? TopP { get; set; }
        /// <summary>A unique identifier representing your end-user, which can help us monitor and detect abuse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequest"/> and sets the default values.
        /// </summary>
        public CreateChatCompletionRequest()
        {
            DisableToolValidation = false;
            FrequencyPenalty = 0;
            Logprobs = false;
            N = 1;
            ParallelToolCalls = true;
            PresencePenalty = 0;
            Stream = false;
            Temperature = 1;
            TopP = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "citation_options", n => { CitationOptions = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCitationOptions>(); } },
                { "compound_custom", n => { CompoundCustom = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom.CreateFromDiscriminatorValue); } },
                { "disable_tool_validation", n => { DisableToolValidation = n.GetBoolValue(); } },
                { "documents", n => { Documents = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionDocument>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionDocument.CreateFromDiscriminatorValue)?.AsList(); } },
                { "exclude_domains", n => { ExcludeDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "frequency_penalty", n => { FrequencyPenalty = n.GetDoubleValue(); } },
                { "function_call", n => { FunctionCall = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestFunctionCall>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestFunctionCall.CreateFromDiscriminatorValue); } },
                { "functions", n => { Functions = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionFunctions>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionFunctions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "include_domains", n => { IncludeDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "include_reasoning", n => { IncludeReasoning = n.GetBoolValue(); } },
                { "logit_bias", n => { LogitBias = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestLogitBiasProperty>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestLogitBiasProperty.CreateFromDiscriminatorValue); } },
                { "logprobs", n => { Logprobs = n.GetBoolValue(); } },
                { "max_completion_tokens", n => { MaxCompletionTokens = n.GetIntValue(); } },
                { "max_tokens", n => { MaxTokens = n.GetIntValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestMessage>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestMetadataProperty>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestMetadataProperty.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestModel>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestModel.CreateFromDiscriminatorValue); } },
                { "n", n => { N = n.GetIntValue(); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetBoolValue(); } },
                { "presence_penalty", n => { PresencePenalty = n.GetDoubleValue(); } },
                { "reasoning_effort", n => { ReasoningEffort = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestReasoningEffort>(); } },
                { "reasoning_format", n => { ReasoningFormat = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestReasoningFormat>(); } },
                { "response_format", n => { ResponseFormat = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestResponseFormat>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestResponseFormat.CreateFromDiscriminatorValue); } },
                { "search_settings", n => { SearchSettings = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestSearchSettings>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestSearchSettings.CreateFromDiscriminatorValue); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "service_tier", n => { ServiceTier = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestServiceTier>(); } },
                { "stop", n => { Stop = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestStop>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestStop.CreateFromDiscriminatorValue); } },
                { "store", n => { Store = n.GetBoolValue(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionTool>(global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "top_logprobs", n => { TopLogprobs = n.GetIntValue(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCitationOptions>("citation_options", CitationOptions);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestCompoundCustom>("compound_custom", CompoundCustom);
            writer.WriteBoolValue("disable_tool_validation", DisableToolValidation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionDocument>("documents", Documents);
            writer.WriteCollectionOfPrimitiveValues<string>("exclude_domains", ExcludeDomains);
            writer.WriteDoubleValue("frequency_penalty", FrequencyPenalty);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestFunctionCall>("function_call", FunctionCall);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionFunctions>("functions", Functions);
            writer.WriteCollectionOfPrimitiveValues<string>("include_domains", IncludeDomains);
            writer.WriteBoolValue("include_reasoning", IncludeReasoning);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestLogitBiasProperty>("logit_bias", LogitBias);
            writer.WriteBoolValue("logprobs", Logprobs);
            writer.WriteIntValue("max_completion_tokens", MaxCompletionTokens);
            writer.WriteIntValue("max_tokens", MaxTokens);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionRequestMessage>("messages", Messages);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestMetadataProperty>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestModel>("model", Model);
            writer.WriteIntValue("n", N);
            writer.WriteBoolValue("parallel_tool_calls", ParallelToolCalls);
            writer.WriteDoubleValue("presence_penalty", PresencePenalty);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestReasoningEffort>("reasoning_effort", ReasoningEffort);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestReasoningFormat>("reasoning_format", ReasoningFormat);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestResponseFormat>("response_format", ResponseFormat);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestSearchSettings>("search_settings", SearchSettings);
            writer.WriteIntValue("seed", Seed);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestServiceTier>("service_tier", ServiceTier);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionRequestStop>("stop", Stop);
            writer.WriteBoolValue("store", Store);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionToolChoiceOption>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ChatCompletionTool>("tools", Tools);
            writer.WriteIntValue("top_logprobs", TopLogprobs);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteStringValue("user", User);
        }
    }
}
#pragma warning restore CS0618
