// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>Specifies the latency tier to use for processing the request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateResponseRequestServiceTier
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        DefaultValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "flex")]
        #pragma warning disable CS1591
        Flex,
        #pragma warning restore CS1591
    }
}
