// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateSpeechRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The text to generate audio for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Input { get; set; }
#nullable restore
#else
        public string Input { get; set; }
#endif
        /// <summary>One of the [available TTS models](/docs/text-to-speech).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestModel? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestModel Model { get; set; }
#endif
        /// <summary>The format of the generated audio. Supported formats are `flac, mp3, mulaw, ogg, wav`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestResponseFormat? ResponseFormat { get; set; }
        /// <summary>The sample rate for generated audio</summary>
        public int? SampleRate { get; set; }
        /// <summary>The speed of the generated audio.</summary>
        public double? Speed { get; set; }
        /// <summary>The voice to use when generating the audio. List of voices can be found [here](/docs/text-to-speech).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Voice { get; set; }
#nullable restore
#else
        public string Voice { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequest"/> and sets the default values.
        /// </summary>
        public CreateSpeechRequest()
        {
            SampleRate = 48000;
            Speed = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "input", n => { Input = n.GetStringValue(); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestModel>(global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestModel.CreateFromDiscriminatorValue); } },
                { "response_format", n => { ResponseFormat = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestResponseFormat>(); } },
                { "sample_rate", n => { SampleRate = n.GetIntValue(); } },
                { "speed", n => { Speed = n.GetDoubleValue(); } },
                { "voice", n => { Voice = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("input", Input);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestModel>("model", Model);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateSpeechRequestResponseFormat>("response_format", ResponseFormat);
            writer.WriteIntValue("sample_rate", SampleRate);
            writer.WriteDoubleValue("speed", Speed);
            writer.WriteStringValue("voice", Voice);
        }
    }
}
#pragma warning restore CS0618
