// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateResponseRequestModelWrapperValue
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gemma2-9b-it")]
        #pragma warning disable CS1591
        Gemma29BIt,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama-3.3-70b-versatile")]
        #pragma warning disable CS1591
        Llama3370BVersatile,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama-3.1-8b-instant")]
        #pragma warning disable CS1591
        Llama318BInstant,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama-guard-3-8b")]
        #pragma warning disable CS1591
        LlamaGuard38B,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama3-70b-8192")]
        #pragma warning disable CS1591
        Llama370B8192,
        #pragma warning restore CS1591
        [EnumMember(Value = "llama3-8b-8192")]
        #pragma warning disable CS1591
        Llama38B8192,
        #pragma warning restore CS1591
    }
}
