// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateEmbeddingResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The list of embeddings generated by the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.Embedding>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.Embedding> Data { get; set; }
#endif
        /// <summary>The name of the model used to generate the embedding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The object type, which is always &quot;list&quot;.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseObject? Object { get; set; }
        /// <summary>The usage information for the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseUsage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponse"/> and sets the default values.
        /// </summary>
        public CreateEmbeddingResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.Embedding>(global::Soenneker.Groq.OpenApiClient.Models.Embedding.CreateFromDiscriminatorValue)?.AsList(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseObject>(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseUsage>(global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseUsage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.Embedding>("data", Data);
            writer.WriteStringValue("model", Model);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseObject>("object", Object);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingResponseUsage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
