// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>qwen3 models support the following valuesSet to &apos;none&apos; to disable reasoning.Set to &apos;default&apos; or null to let Qwen reason.openai/gpt-oss-20b and openai/gpt-oss-120b support &apos;low&apos;, &apos;medium&apos;, or &apos;high&apos;.&apos;medium&apos; is the default value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateChatCompletionRequestReasoningEffort
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        DefaultValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "high")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
    }
}
