// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Represents a response returned by model, based on the provided input.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateResponseResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the response was generated in the background.</summary>
        public bool? Background { get; set; }
        /// <summary>The Unix timestamp (in seconds) of when the response was created.</summary>
        public int? CreatedAt { get; set; }
        /// <summary>An error object if the response failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseError Error { get; set; }
#endif
        /// <summary>A unique identifier for the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Details about why the response is incomplete.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseIncompleteDetails? IncompleteDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseIncompleteDetails IncompleteDetails { get; set; }
#endif
        /// <summary>The system instructions used for the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>The maximum number of tokens configured for the response.</summary>
        public int? MaxOutputTokens { get; set; }
        /// <summary>The maximum number of tool calls allowed.</summary>
        public int? MaxToolCalls { get; set; }
        /// <summary>Metadata attached to the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseMetadata Metadata { get; set; }
#endif
        /// <summary>The model used for the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The object type, which is always `response`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseObject? Object { get; set; }
        /// <summary>An array of content items generated by the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem>? Output { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem> Output { get; set; }
#endif
        /// <summary>Whether the model can run tool calls in parallel.</summary>
        public bool? ParallelToolCalls { get; set; }
        /// <summary>Not supported. Always null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousResponseId { get; set; }
#nullable restore
#else
        public string PreviousResponseId { get; set; }
#endif
        /// <summary>Configuration options for [models that support reasoning](https://console.groq.com/docs/reasoning).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseReasoning? Reasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseReasoning Reasoning { get; set; }
#endif
        /// <summary>The service tier used for processing.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseServiceTier? ServiceTier { get; set; }
        /// <summary>The status of the response generation. One of `completed`, `failed`, `in_progress`, or `incomplete`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseStatus? Status { get; set; }
        /// <summary>Whether the response was stored.</summary>
        public bool? Store { get; set; }
        /// <summary>The sampling temperature used.</summary>
        public double? Temperature { get; set; }
        /// <summary>Text format configuration used for the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseText Text { get; set; }
#endif
        /// <summary>&quot;Controls which (if any) tool is called by the model.`none` means the model will not call any tool and instead generates a message.`auto` means the model can pick between generating a message or calling one or more tools.`required` means the model must call one or more tools.Specifying a particular tool via `{\&quot;type\&quot;: \&quot;function\&quot;, \&quot;function\&quot;: {\&quot;name\&quot;: \&quot;my_function\&quot;}}` forces the model to call that tool.`none` is the default when no tools are present. `auto` is the default if tools are present.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption ToolChoice { get; set; }
#endif
        /// <summary>The tools that were available to the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool> Tools { get; set; }
#endif
        /// <summary>The number of top log probabilities returned.</summary>
        public int? TopLogprobs { get; set; }
        /// <summary>The nucleus sampling parameter used.</summary>
        public double? TopP { get; set; }
        /// <summary>The truncation strategy used.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseTruncation? Truncation { get; set; }
        /// <summary>Usage statistics for the response request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage Usage { get; set; }
#endif
        /// <summary>The user identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponse"/> and sets the default values.
        /// </summary>
        public CreateResponseResponse()
        {
            AdditionalData = new Dictionary<string, object>();
            Background = false;
            TopLogprobs = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background", n => { Background = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseError>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseError.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "incomplete_details", n => { IncompleteDetails = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseIncompleteDetails>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseIncompleteDetails.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetIntValue(); } },
                { "max_tool_calls", n => { MaxToolCalls = n.GetIntValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseMetadata>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseMetadata.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseObject>(); } },
                { "output", n => { Output = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem>(global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetBoolValue(); } },
                { "previous_response_id", n => { PreviousResponseId = n.GetStringValue(); } },
                { "reasoning", n => { Reasoning = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseReasoning>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseReasoning.CreateFromDiscriminatorValue); } },
                { "service_tier", n => { ServiceTier = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseServiceTier>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseStatus>(); } },
                { "store", n => { Store = n.GetBoolValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseText>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseText.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption>(global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool>(global::Soenneker.Groq.OpenApiClient.Models.ResponseTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "top_logprobs", n => { TopLogprobs = n.GetIntValue(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
                { "truncation", n => { Truncation = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseTruncation>(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage>(global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("background", Background);
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseError>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseIncompleteDetails>("incomplete_details", IncompleteDetails);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteIntValue("max_output_tokens", MaxOutputTokens);
            writer.WriteIntValue("max_tool_calls", MaxToolCalls);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseMetadata>("metadata", Metadata);
            writer.WriteStringValue("model", Model);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseObject>("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem>("output", Output);
            writer.WriteBoolValue("parallel_tool_calls", ParallelToolCalls);
            writer.WriteStringValue("previous_response_id", PreviousResponseId);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseReasoning>("reasoning", Reasoning);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseServiceTier>("service_tier", ServiceTier);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseStatus>("status", Status);
            writer.WriteBoolValue("store", Store);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseText>("text", Text);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool>("tools", Tools);
            writer.WriteIntValue("top_logprobs", TopLogprobs);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseResponseTruncation>("truncation", Truncation);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage>("usage", Usage);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
