// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>Specifies how to output reasoning tokensThis field is mutually exclusive with `include_reasoning`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateChatCompletionRequestReasoningFormat
    {
        [EnumMember(Value = "hidden")]
        #pragma warning disable CS1591
        Hidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "raw")]
        #pragma warning disable CS1591
        Raw,
        #pragma warning restore CS1591
        [EnumMember(Value = "parsed")]
        #pragma warning disable CS1591
        Parsed,
        #pragma warning restore CS1591
    }
}
