// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The format to return the embeddings in. Can only be `float` or `base64`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateEmbeddingRequestEncodingFormat
    {
        [EnumMember(Value = "float")]
        #pragma warning disable CS1591
        FloatValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "base64")]
        #pragma warning disable CS1591
        Base64,
        #pragma warning restore CS1591
    }
}
