// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The service tier to use for the request. Defaults to `on_demand`.- `auto` will automatically select the highest tier available within the rate limits of your organization.- `flex` uses the flex tier, which will succeed or fail quickly.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateChatCompletionRequestServiceTier
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "on_demand")]
        #pragma warning disable CS1591
        OnDemand,
        #pragma warning restore CS1591
        [EnumMember(Value = "flex")]
        #pragma warning disable CS1591
        Flex,
        #pragma warning restore CS1591
        [EnumMember(Value = "performance")]
        #pragma warning disable CS1591
        Performance,
        #pragma warning restore CS1591
    }
}
