// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateEmbeddingRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The format to return the embeddings in. Can only be `float` or `base64`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestEncodingFormat? EncodingFormat { get; set; }
        /// <summary>Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model, cannot be an empty string, and any array must be 2048 dimensions or less.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestInput? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestInput Input { get; set; }
#endif
        /// <summary>ID of the model to use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestModel? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestModel Model { get; set; }
#endif
        /// <summary>A unique identifier representing your end-user, which can help us monitor and detect abuse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "encoding_format", n => { EncodingFormat = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestEncodingFormat>(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestInput>(global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestInput.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestModel>(global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestModel.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestEncodingFormat>("encoding_format", EncodingFormat);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestInput>("input", Input);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateEmbeddingRequestModel>("model", Model);
            writer.WriteStringValue("user", User);
        }
    }
}
#pragma warning restore CS0618
