// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateResponseRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Text input to the model, used to generate a response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestInput? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestInput Input { get; set; }
#endif
        /// <summary>Inserts a system (or developer) message as the first item in the model&apos;s context.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>An upper bound for the number of tokens that can be generated for a response, including visible output tokens and reasoning tokens.</summary>
        public int? MaxOutputTokens { get; set; }
        /// <summary>Custom key-value pairs for storing additional information. Maximum of 16 pairs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestMetadataProperty Metadata { get; set; }
#endif
        /// <summary>ID of the model to use. For details on which models are compatible with the Responses API, see available [models](https://console.groq.com/docs/models)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestModel? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestModel Model { get; set; }
#endif
        /// <summary>Enable parallel execution of multiple tool calls.</summary>
        public bool? ParallelToolCalls { get; set; }
        /// <summary>Configuration for reasoning capabilities when using [models that support reasoning](https://console.groq.com/docs/reasoning).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestReasoning? Reasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestReasoning Reasoning { get; set; }
#endif
        /// <summary>Specifies the latency tier to use for processing the request.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestServiceTier? ServiceTier { get; set; }
        /// <summary>Response storage flag. Note: Currently only supports false or null values.</summary>
        public bool? Store { get; set; }
        /// <summary>Enable streaming mode to receive response data as server-sent events.</summary>
        public bool? Stream { get; set; }
        /// <summary>Controls randomness in the response generation. Range: 0 to 2. Lower values produce more deterministic outputs, higher values increase variety and creativity.</summary>
        public double? Temperature { get; set; }
        /// <summary>Response format configuration. Supports plain text or structured JSON output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestText Text { get; set; }
#endif
        /// <summary>Controls which (if any) tool is called by the model.`none` means the model will not call any tool and instead generates a message.`auto` means the model can pick between generating a message or calling one or more tools.`required` means the model must call one or more tools.Specifying a particular tool via `{&quot;type&quot;: &quot;function&quot;, &quot;function&quot;: {&quot;name&quot;: &quot;my_function&quot;}}` forces the model to call that tool.`none` is the default when no tools are present. `auto` is the default if tools are present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption ToolChoice { get; set; }
#endif
        /// <summary>List of tools available to the model. Currently supports function definitions only. Maximum of 128 functions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool> Tools { get; set; }
#endif
        /// <summary>Nucleus sampling parameter that controls the cumulative probability cutoff. Range: 0 to 1. A value of 0.1 restricts sampling to tokens within the top 10% probability mass.</summary>
        public double? TopP { get; set; }
        /// <summary>Context truncation strategy. Supported values: `auto` or `disabled`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestTruncation? Truncation { get; set; }
        /// <summary>Optional identifier for tracking end-user requests. Useful for usage monitoring and compliance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequest"/> and sets the default values.
        /// </summary>
        public CreateResponseRequest()
        {
            ParallelToolCalls = true;
            Store = false;
            Stream = false;
            Temperature = 1;
            TopP = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestInput>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestInput.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetIntValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestMetadataProperty>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestMetadataProperty.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestModel>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestModel.CreateFromDiscriminatorValue); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetBoolValue(); } },
                { "reasoning", n => { Reasoning = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestReasoning>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestReasoning.CreateFromDiscriminatorValue); } },
                { "service_tier", n => { ServiceTier = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestServiceTier>(); } },
                { "store", n => { Store = n.GetBoolValue(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestText>(global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestText.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption>(global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool>(global::Soenneker.Groq.OpenApiClient.Models.ResponseTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
                { "truncation", n => { Truncation = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestTruncation>(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestInput>("input", Input);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteIntValue("max_output_tokens", MaxOutputTokens);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestMetadataProperty>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestModel>("model", Model);
            writer.WriteBoolValue("parallel_tool_calls", ParallelToolCalls);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestReasoning>("reasoning", Reasoning);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestServiceTier>("service_tier", ServiceTier);
            writer.WriteBoolValue("store", Store);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestText>("text", Text);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseTool>("tools", Tools);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateResponseRequestTruncation>("truncation", Truncation);
            writer.WriteStringValue("user", User);
        }
    }
}
#pragma warning restore CS0618
