// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>&quot;The format of the transcript output, in one of these options: `json`, `text`, or `verbose_json`.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateTranslationRequestResponseFormat
    {
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "verbose_json")]
        #pragma warning disable CS1591
        VerboseJson,
        #pragma warning restore CS1591
    }
}
