// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The format of the generated audio. Supported formats are `flac, mp3, mulaw, ogg, wav`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateSpeechRequestResponseFormat
    {
        [EnumMember(Value = "flac")]
        #pragma warning disable CS1591
        Flac,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3")]
        #pragma warning disable CS1591
        Mp3,
        #pragma warning restore CS1591
        [EnumMember(Value = "mulaw")]
        #pragma warning disable CS1591
        Mulaw,
        #pragma warning restore CS1591
        [EnumMember(Value = "ogg")]
        #pragma warning disable CS1591
        Ogg,
        #pragma warning restore CS1591
        [EnumMember(Value = "wav")]
        #pragma warning disable CS1591
        Wav,
        #pragma warning restore CS1591
    }
}
