// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Represents a chat completion response returned by model, based on the provided input.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateChatCompletionResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of chat completion choices. Can be more than one if `n` is greater than 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseChoicesItem>? Choices { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseChoicesItem> Choices { get; set; }
#endif
        /// <summary>The Unix timestamp (in seconds) of when the chat completion was created.</summary>
        public int? Created { get; set; }
        /// <summary>A unique identifier for the chat completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>List of discovered MCP tools from connected servers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseMcpListToolsItem>? McpListTools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseMcpListToolsItem> McpListTools { get; set; }
#endif
        /// <summary>The model used for the chat completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The object type, which is always `chat.completion`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseObject? Object { get; set; }
        /// <summary>The service tier used for the request.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseServiceTier? ServiceTier { get; set; }
        /// <summary>This fingerprint represents the backend configuration that the model runs with.Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemFingerprint { get; set; }
#nullable restore
#else
        public string SystemFingerprint { get; set; }
#endif
        /// <summary>Usage statistics for the completion request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage Usage { get; set; }
#endif
        /// <summary>Detailed usage breakdown by model when multiple models are used in the request for compound AI systems.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseUsageBreakdown? UsageBreakdown { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseUsageBreakdown UsageBreakdown { get; set; }
#endif
        /// <summary>Groq-specific metadata for non-streaming chat completion responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming? XGroq { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming XGroq { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponse"/> and sets the default values.
        /// </summary>
        public CreateChatCompletionResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "choices", n => { Choices = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseChoicesItem>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseChoicesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created", n => { Created = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mcp_list_tools", n => { McpListTools = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseMcpListToolsItem>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseMcpListToolsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseObject>(); } },
                { "service_tier", n => { ServiceTier = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseServiceTier>(); } },
                { "system_fingerprint", n => { SystemFingerprint = n.GetStringValue(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage>(global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage.CreateFromDiscriminatorValue); } },
                { "usage_breakdown", n => { UsageBreakdown = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseUsageBreakdown>(global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseUsageBreakdown.CreateFromDiscriminatorValue); } },
                { "x_groq", n => { XGroq = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming>(global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseChoicesItem>("choices", Choices);
            writer.WriteIntValue("created", Created);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseMcpListToolsItem>("mcp_list_tools", McpListTools);
            writer.WriteStringValue("model", Model);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseObject>("object", Object);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseServiceTier>("service_tier", ServiceTier);
            writer.WriteStringValue("system_fingerprint", SystemFingerprint);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CompletionUsage>("usage", Usage);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.CreateChatCompletionResponseUsageBreakdown>("usage_breakdown", UsageBreakdown);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming>("x_groq", XGroq);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
