// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The intended purpose of the file. Supported values are `batch`, and `batch_output`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FilePurpose
    {
        [EnumMember(Value = "batch")]
        #pragma warning disable CS1591
        Batch,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch_output")]
        #pragma warning disable CS1591
        BatchOutput,
        #pragma warning restore CS1591
    }
}
