// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReadFineTuningResponseData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>BaseModel is the model that the fine tune was originally trained on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseModel { get; set; }
#nullable restore
#else
        public string BaseModel { get; set; }
#endif
        /// <summary>CreatedAt is the timestamp of when the fine tuned model was created.</summary>
        public double? CreatedAt { get; set; }
        /// <summary>FineTunedModel is the final name of the fine tuned model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FineTunedModel { get; set; }
#nullable restore
#else
        public string FineTunedModel { get; set; }
#endif
        /// <summary>ID is the unique identifier of a fine tune.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>InputFileID is the id of the file that was uploaded via the /files api.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputFileId { get; set; }
#nullable restore
#else
        public string InputFileId { get; set; }
#endif
        /// <summary>Name is the given name to a fine tuned model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Type is the type of fine tuning format such as &quot;lora&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ReadFineTuningResponseData"/> and sets the default values.
        /// </summary>
        public ReadFineTuningResponseData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ReadFineTuningResponseData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ReadFineTuningResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ReadFineTuningResponseData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_model", n => { BaseModel = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDoubleValue(); } },
                { "fine_tuned_model", n => { FineTunedModel = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input_file_id", n => { InputFileId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("base_model", BaseModel);
            writer.WriteDoubleValue("created_at", CreatedAt);
            writer.WriteStringValue("fine_tuned_model", FineTunedModel);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("input_file_id", InputFileId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
