// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseFileCitation"/>, <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseUrlCitation"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseAnnotation : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseFileCitation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseFileCitation? ResponseFileCitation { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseFileCitation ResponseFileCitation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseUrlCitation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUrlCitation? ResponseUrlCitation { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUrlCitation ResponseUrlCitation { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseAnnotation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ResponseAnnotation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Groq.OpenApiClient.Models.ResponseAnnotation();
            if("file_citation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseFileCitation = new global::Soenneker.Groq.OpenApiClient.Models.ResponseFileCitation();
            }
            else if("ResponseUrlCitation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseUrlCitation = new global::Soenneker.Groq.OpenApiClient.Models.ResponseUrlCitation();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ResponseFileCitation != null)
            {
                return ResponseFileCitation.GetFieldDeserializers();
            }
            else if(ResponseUrlCitation != null)
            {
                return ResponseUrlCitation.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ResponseFileCitation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseFileCitation>(null, ResponseFileCitation);
            }
            else if(ResponseUrlCitation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUrlCitation>(null, ResponseUrlCitation);
            }
        }
    }
}
#pragma warning restore CS0618
