// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseNamedToolChoice"/>, <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOptionWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseToolChoiceOption : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseNamedToolChoice"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseNamedToolChoice? ResponseNamedToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseNamedToolChoice ResponseNamedToolChoice { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOptionWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOptionWrapper? ResponseToolChoiceOptionWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOptionWrapper ResponseToolChoiceOptionWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOption();
            if("ResponseNamedToolChoice".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseNamedToolChoice = new global::Soenneker.Groq.OpenApiClient.Models.ResponseNamedToolChoice();
            }
            else if("ResponseToolChoiceOptionWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseToolChoiceOptionWrapper = new global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOptionWrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ResponseNamedToolChoice != null)
            {
                return ResponseNamedToolChoice.GetFieldDeserializers();
            }
            else if(ResponseToolChoiceOptionWrapper != null)
            {
                return ResponseToolChoiceOptionWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ResponseNamedToolChoice != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseNamedToolChoice>(null, ResponseNamedToolChoice);
            }
            else if(ResponseToolChoiceOptionWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolChoiceOptionWrapper>(null, ResponseToolChoiceOptionWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
