// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Usage statistics for the response request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseUsage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of tokens in the input.</summary>
        public int? InputTokens { get; set; }
        /// <summary>Breakdown of input tokens.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageInputTokensDetails? InputTokensDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageInputTokensDetails InputTokensDetails { get; set; }
#endif
        /// <summary>Number of tokens in the generated output.</summary>
        public int? OutputTokens { get; set; }
        /// <summary>Breakdown of output tokens.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageOutputTokensDetails? OutputTokensDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageOutputTokensDetails OutputTokensDetails { get; set; }
#endif
        /// <summary>Total number of tokens used in the request (input + output).</summary>
        public int? TotalTokens { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage"/> and sets the default values.
        /// </summary>
        public ResponseUsage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ResponseUsage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "input_tokens", n => { InputTokens = n.GetIntValue(); } },
                { "input_tokens_details", n => { InputTokensDetails = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageInputTokensDetails>(global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageInputTokensDetails.CreateFromDiscriminatorValue); } },
                { "output_tokens", n => { OutputTokens = n.GetIntValue(); } },
                { "output_tokens_details", n => { OutputTokensDetails = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageOutputTokensDetails>(global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageOutputTokensDetails.CreateFromDiscriminatorValue); } },
                { "total_tokens", n => { TotalTokens = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("input_tokens", InputTokens);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageInputTokensDetails>("input_tokens_details", InputTokensDetails);
            writer.WriteIntValue("output_tokens", OutputTokens);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseUsageOutputTokensDetails>("output_tokens_details", OutputTokensDetails);
            writer.WriteIntValue("total_tokens", TotalTokens);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
