// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// An output message from the model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseOutputMessage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content of the output message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputContent>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputContent> Content { get; set; }
#endif
        /// <summary>The unique ID of the output message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The role of the output message. Always `assistant`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageRole? Role { get; set; }
        /// <summary>The status of the message.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageStatus? Status { get; set; }
        /// <summary>The type of the output message. Always `message`.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage"/> and sets the default values.
        /// </summary>
        public ResponseOutputMessage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputContent>(global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputContent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageRole>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputContent>("content", Content);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageRole>("role", Role);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessageType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
