// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResponseTool : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Describes the function&apos;s purpose. The model uses this to determine when to invoke the function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Function parameters defined as a JSON Schema object. Refer to https://json-schema.org/understanding-json-schema/ for schema documentation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolParameters? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolParameters Parameters { get; set; }
#endif
        /// <summary>Whether to enable strict schema adherence when generating the function call.</summary>
        public bool? Strict { get; set; }
        /// <summary>The type of the tool. Currently, only `function` is supported.</summary>
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseToolType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseTool"/> and sets the default values.
        /// </summary>
        public ResponseTool()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseTool"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ResponseTool CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.ResponseTool();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolParameters>(global::Soenneker.Groq.OpenApiClient.Models.ResponseToolParameters.CreateFromDiscriminatorValue); } },
                { "strict", n => { Strict = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolParameters>("parameters", Parameters);
            writer.WriteBoolValue("strict", Strict);
            writer.WriteEnumValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseToolType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
