// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputFunctionCall"/>, <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage"/>, <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputReasoning"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseOutputItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputFunctionCall"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputFunctionCall? ResponseOutputFunctionCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputFunctionCall ResponseOutputFunctionCall { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage? ResponseOutputMessage { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage ResponseOutputMessage { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputReasoning"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputReasoning? ResponseOutputReasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputReasoning ResponseOutputReasoning { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputItem();
            if("function_call".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseOutputFunctionCall = new global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputFunctionCall();
            }
            else if("message".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseOutputMessage = new global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage();
            }
            else if("reasoning".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ResponseOutputReasoning = new global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputReasoning();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ResponseOutputFunctionCall != null)
            {
                return ResponseOutputFunctionCall.GetFieldDeserializers();
            }
            else if(ResponseOutputMessage != null)
            {
                return ResponseOutputMessage.GetFieldDeserializers();
            }
            else if(ResponseOutputReasoning != null)
            {
                return ResponseOutputReasoning.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ResponseOutputFunctionCall != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputFunctionCall>(null, ResponseOutputFunctionCall);
            }
            else if(ResponseOutputMessage != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputMessage>(null, ResponseOutputMessage);
            }
            else if(ResponseOutputReasoning != null)
            {
                writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.ResponseOutputReasoning>(null, ResponseOutputReasoning);
            }
        }
    }
}
#pragma warning restore CS0618
