// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>The type of the function call. Always `function_call`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ResponseOutputFunctionCallType
    {
        [EnumMember(Value = "function_call")]
        #pragma warning disable CS1591
        FunctionCall,
        #pragma warning restore CS1591
    }
}
