// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    /// <summary>
    /// Groq-specific metadata for non-streaming chat completion responses.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class XGroqNonStreaming : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The debug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug? Debug { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug Debug { get; set; }
#endif
        /// <summary>A groq request ID which can be used to refer to a specific request to groq support.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The seed used for the request. See the seed property on CreateChatCompletionRequest for more details.</summary>
        public int? Seed { get; set; }
        /// <summary>Additional Groq-specific usage metrics (hardware cache statistics).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingUsage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming"/> and sets the default values.
        /// </summary>
        public XGroqNonStreaming()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreaming();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "debug", n => { Debug = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug>(global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingUsage>(global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingUsage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug>("debug", Debug);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingUsage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
