// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Groq.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class XGroqNonStreamingDebug : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Token IDs for the input.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? InputTokenIds { get; set; }
#nullable restore
#else
        public List<int?> InputTokenIds { get; set; }
#endif
        /// <summary>Token strings for the input.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? InputTokens { get; set; }
#nullable restore
#else
        public List<string> InputTokens { get; set; }
#endif
        /// <summary>Token IDs for the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? OutputTokenIds { get; set; }
#nullable restore
#else
        public List<int?> OutputTokenIds { get; set; }
#endif
        /// <summary>Token strings for the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OutputTokens { get; set; }
#nullable restore
#else
        public List<string> OutputTokens { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug"/> and sets the default values.
        /// </summary>
        public XGroqNonStreamingDebug()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Groq.OpenApiClient.Models.XGroqNonStreamingDebug();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "input_token_ids", n => { InputTokenIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "input_tokens", n => { InputTokens = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "output_token_ids", n => { OutputTokenIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "output_tokens", n => { OutputTokens = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("input_token_ids", InputTokenIds);
            writer.WriteCollectionOfPrimitiveValues<string>("input_tokens", InputTokens);
            writer.WriteCollectionOfPrimitiveValues<int?>("output_token_ids", OutputTokenIds);
            writer.WriteCollectionOfPrimitiveValues<string>("output_tokens", OutputTokens);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
